In [5]:
import pandas as pd

## Pandas Versions ##

In [6]:
pd.__version__

'2.0.3'

## Read CSV file ##

In [7]:
df = pd.read_csv('.\datasets\housing.csv')

## Get number of columns ##

In [8]:
df.shape

(20640, 10)

In [9]:
df.info

<bound method DataFrame.info of        longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  

## Columns with missing data ##

In [10]:
missing_values = df.isnull()

In [11]:
missing_counts = missing_values.sum()

In [12]:
print(missing_counts[missing_counts > 0].index.tolist())

['total_bedrooms']


## Number of Unique values in the 'ocean_proximity' column

In [13]:
ocean_proximity_values = df['ocean_proximity']
print(ocean_proximity_values.nunique())

5


## Average value of the 'median_house_value' for the houses near the bay ##

In [14]:
df_houses_near_bay = df[df['ocean_proximity'] == 'NEAR BAY']
avg_value_median_house_value = df_houses_near_bay['median_house_value'].mean()
avg_value_median_house_value

259212.31179039303

## Has the mean value changed after filling missing values? ##

In [15]:
# find mean before missing values
average_bedrooms_before = df['total_bedrooms'].mean()
average_bedrooms_before





537.8705525375618

In [16]:
# find mean after filling for missing values
filled_values = df['total_bedrooms'].fillna(average_bedrooms_before)
average_bedrooms_after = filled_values.mean()
average_bedrooms_after

537.8705525375617

## Value of the last element of w ##*

In [17]:
import numpy as np
# options located on islands
df_houses_on_islands = df[df['ocean_proximity'] == 'ISLAND']
X = df_houses_on_islands[['housing_median_age', 'total_rooms','total_bedrooms']].values
print('X')
print(X)

X
[[  27. 1675.  521.]
 [  52. 2359.  591.]
 [  52. 2127.  512.]
 [  52.  996.  264.]
 [  29.  716.  214.]]


In [18]:
XT = X.T
XT

array([[  27.,   52.,   52.,   52.,   29.],
       [1675., 2359., 2127.,  996.,  716.],
       [ 521.,  591.,  512.,  264.,  214.]])

In [19]:
X.shape

(5, 3)

In [20]:
XT.shape

(3, 5)

In [21]:
XTX = np.dot(XT, X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [22]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv, XTX_inv.sum()

(array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
        [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
        [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]]),
 0.0010083530589819155)

In [23]:
y = [950, 1300, 800, 1000, 1300]

In [24]:
w = np.dot(np.dot(XTX_inv,XT),y)

In [25]:
first_element = w[0]
first_element

23.123309612152052